from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class DuelAssets: 


	# Click Rule Assets
	# 战斗数据 
	C_D_BATTLE_DATA = RuleClick(roi_front=(584,279,100,100), roi_back=(584,279,100,100), name="d_battle_data")


	# Image Rule Assets
	# 点击阵容 
	I_D_TEAM = RuleImage(roi_front=(813,284,34,74), roi_back=(813,284,50,100), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_team.png")
	# 一键切换所有的御魂 
	I_D_TEAM_SWTICH = RuleImage(roi_front=(1082,85,38,41), roi_back=(1082,85,38,41), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_team_swtich.png")
	# 观战 
	I_D_VISIT = RuleImage(roi_front=(1045,613,53,55), roi_back=(1045,613,53,55), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_visit.png")
	# description 
	I_D_BATTLE = RuleImage(roi_front=(1153,573,100,100), roi_back=(1123,537,154,177), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_battle.png")
	# 战斗带保护的 
	I_D_BATTLE_PROTECT = RuleImage(roi_front=(1153,578,100,100), roi_back=(1118,553,155,149), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_battle_protect.png")
	# 预选点击确认 
	I_D_CONFIRM = RuleImage(roi_front=(1097,517,139,156), roi_back=(1097,517,139,156), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_confirm.png")
	# 自动上阵 
	I_D_AUTO_ENTRY = RuleImage(roi_front=(30,127,66,62), roi_back=(20,119,115,111), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_auto_entry.png")
	# 手动，弃用 
	I_D_HAND = RuleImage(roi_front=(34,635,55,55), roi_back=(34,635,55,55), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_hand.png")
	# 主界面的感叹号 
	I_D_HELP = RuleImage(roi_front=(719,434,32,30), roi_back=(680,400,80,80), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_help.png")
	# 准备 
	I_D_PREPARE = RuleImage(roi_front=(1127,541,100,100), roi_back=(1127,541,100,100), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_prepare.png")
	# 准备完毕 
	I_D_PREPARE_DONE = RuleImage(roi_front=(495,82,75,55), roi_back=(495,82,75,55), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_prepare_done.png")
	# 战斗数据 
	I_D_BATTLE_DATA = RuleImage(roi_front=(1068,610,38,60), roi_back=(1068,610,38,60), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_battle_data.png")
	# 胜利 
	I_D_VICTORY = RuleImage(roi_front=(466,88.33333333333331,95,95), roi_back=(433,55.333333333333314,160,165), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_victory.png")
	# 失败 
	I_D_FAIL = RuleImage(roi_front=(422,66,100,100), roi_back=(422,66,100,100), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_fail.png")
	# 战 
	I_D_WORD_BATTLE = RuleImage(roi_front=(612,41,54,54), roi_back=(612,41,54,54), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_word_battle.png")
	# 名士的星星 
	I_D_CELEB_STAR = RuleImage(roi_front=(586,456,30,32), roi_back=(574,444,53,54), threshold=0.75, method="Template matching", file="./tasks/Duel/duel/duel_d_celeb_star.png")
	# 名士专属 
	I_D_CELEB_HONOR = RuleImage(roi_front=(665,531,25,30), roi_back=(652,517,52,53), threshold=0.75, method="Template matching", file="./tasks/Duel/duel/duel_d_celeb_honor.png")
	# 练 
	I_BATTLE_WITH_TRAIN = RuleImage(roi_front=(1161,588,78,81), roi_back=(1114,547,163,172), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_battle_with_train.png")
	# 活动的战斗按钮 
	I_D_BATTLE2 = RuleImage(roi_front=(1171,592,69,78), roi_back=(1119,566,154,143), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_battle2.png")
	# 名士的BAN卡環節
	I_D_CELEB_BATTLE_BAN = RuleImage(roi_front=(611,39,55,59), roi_back=(611,39,55,59), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_celeb_battle_ban.png")
	# 名士的BAN卡 鎖定
	I_D_CELEB_BAN_LOCK = RuleImage(roi_front=(1090,556,152,59), roi_back=(1090,556,152,59), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_celeb_ban_lock.png")
	# 名士的BAN卡 SHORT
	I_D_CELEB_BAN_SHORT = RuleImage(roi_front=(714,241,34,61), roi_back=(714,241,34,61), threshold=0.9, method="Template matching", file="./tasks/Duel/duel/duel_d_celeb_ban_short.png")
	# 名士的MY BAN卡 SHORT
	I_D_CELEB_MY_BAN_SHORT = RuleImage(roi_front=(138,241,34,61), roi_back=(138,241,34,61), threshold=0.9, method="Template matching", file="./tasks/Duel/duel/duel_d_celeb_MY_ban_short.png")
	# 名士的BAN卡 言靈
	I_D_CELEB_BAN_YANLIN = RuleImage(roi_front=(718,136,26,143), roi_back=(718,136,26,143), threshold=0.9, method="Template matching", file="./tasks/Duel/duel/duel_d_celeb_ban_yanlin.png")


	# Ocr Rule Assets
	# 荣誉 
	O_D_HONOR = RuleOcr(roi=(699,562,131,31), area=(699,562,131,31), mode="DigitCounter", method="Default", keyword="", name="d_honor")
	# 分数 
	O_D_SCORE = RuleOcr(roi=(703,516,54,26), area=(703,516,54,26), mode="Digit", method="Default", keyword="", name="d_score")
	# 手動 
	O_D_HAND = RuleOcr(roi=(31,639,63,45), area=(31,639,63,45), mode="Single", method="Default", keyword="手勤", name="d_hand")
	# 自動 
	O_D_AUTO = RuleOcr(roi=(30,640,65,44), area=(30,640,65,44), mode="Single", method="Default", keyword="自勤", name="d_auto")
	# 名士局的禁用腳色
	O_D_CELEB_BAN_WHO = RuleOcr(roi=(714,163,34,139), area=(714,163,34,139), mode="Single", method="Default", keyword="", name="d_celeb_ban_who")
	# MY名士局的禁用腳色
	O_D_CELEB_MY_BAN_WHO_S = RuleOcr(roi=(138,163,34,139), area=(138,163,34,139), mode="Single", method="Default", keyword="", name="d_celeb_my_ban_who")
	# 名士局的禁用腳色
	O_D_CELEB_BAN_WHO_SHORT = RuleOcr(roi=(713,179,34,61), area=(713,179,34,61), mode="Single", method="Default", keyword="", name="d_celeb_ban_who_short")
	# MY名士局的禁用腳色
	O_D_CELEB_MY_BAN_WHO_SHORT = RuleOcr(roi=(138,184,34,58), area=(138,184,34,58), mode="Single", method="Default", keyword="", name="d_celeb_my_ban_who_short")


