from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class SwitchOnmyojiAssets: 


	# Image Rule Assets
	# 晴明战标志 
	I_SEIMI_BATTLE = RuleImage(roi_front=(263,435,60,75), roi_back=(263,435,60,75), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchOnmyoji/so/so_qm_zhan.png")
	# 神乐战标志 
	I_KAGURA_BATTLE = RuleImage(roi_front=(520,434,60,75), roi_back=(520,434,60,75), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchOnmyoji/so/so_sl_zhan.png")
	# 源博雅战标志 
	I_HIROMASA_BATTLE = RuleImage(roi_front=(775,435,60,75), roi_back=(775,435,60,75), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchOnmyoji/so/so_yby_zhan.png")
	# 八百比丘尼战标志 
	I_YAO_BIKUNI_BATTLE = RuleImage(roi_front=(1030,437,60,75), roi_back=(1030,437,60,75), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchOnmyoji/so/so_bbbqn_zhan.png")
	# 阴阳师交替按钮 
	I_ONMYOJI_SWITCH = RuleImage(roi_front=(32,380,52,42), roi_back=(32,380,52,42), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchOnmyoji/so/so_jiaoti.png")
	# 阴阳术阴阳师页面标志 
	I_ONMYOJI_CHECK = RuleImage(roi_front=(80,615,58,67), roi_back=(80,615,58,67), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchOnmyoji/so/so_yinyangshi.png")
	# 阴阳术英杰页面标志 
	I_HERO_CHECK = RuleImage(roi_front=(80,615,58,67), roi_back=(80,615,58,67), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchOnmyoji/so/so_yingjie.png")


